# -*- coding: utf-8 -*-
"""Multiple Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D6a-WnlL7OP76nBIARsqRRDqLNMPC5x5

# Multiple Linear Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('../../data/seasons/score/2008-18.csv')
X = dataset.iloc[:, 1:-2].values
y = dataset.iloc[:, -2:].values
print(type(X), X, len(X))
print(type(y), y, len(y))

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

"""## Training the Multiple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),2), y_test.reshape(len(y_test),2)),1))

"""## Evaluating the Model Performance"""

from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred))
print(regressor.predict([[115.0, 114.3, 0.45280000000000004, 0.3868, 0.8552, 42.0, 11.1, 6.1, 0.6, 1525.012443981673, 117.5, 114.1, 0.48050000000000004, 0.4142, 0.7729000000000001, 48.2, 16.5, 4.4, 0.7, 1611.0511901230773]]))