# -*- coding: utf-8 -*-
"""Polynomial Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yb050xqL8yWOFQXFoiDXdgIijL3spoVd

# Polynomial Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('../../data/seasons/score/2010-2018.csv')
X = dataset.iloc[:, 4:-2].values
y = dataset.iloc[:, -2:].values
print(X)
print(y)

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

"""## Training the Polynomial Regression model on the Training set"""

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

"""## Predicting the Test set results"""

y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),2), y_test.reshape(len(y_test),2)),1))

"""## Evaluating the Model Performance"""

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

"""Prevendo Um Resultado"""

print(regressor.predict(poly_reg.transform([[115.0, 114.3, 0.45280000000000004, 0.3868, 0.8552, 42.0, 11.1, 6.1, 0.6, 1525.012443981673, 117.5, 114.1, 0.48050000000000004, 0.4142, 0.7729000000000001, 48.2, 16.5, 4.4, 0.7, 1611.0511901230773]])))