# -*- coding: utf-8 -*-
"""Random Forest Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gspl2Ny6bDH977tPODOTa2_gLvgqG4-4

# Random Forest Regression

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('../../data/seasons/score/2018-2018.csv')
X = dataset.iloc[:, 4:-2].values
y = dataset.iloc[:, -2:].values
print(dataset.iloc[:, :-2].columns)

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

"""## Training the Random Forest Regression model on the whole dataset"""

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 250, random_state = 0)
regressor.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
# print(np.concatenate((y_pred.reshape(len(y_pred),2), y_test.reshape(len(y_test),2)),1))

"""## Evaluating the Model Performance"""

from sklearn.metrics import r2_score, mean_squared_error
print(r2_score(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
# print(regressor.predict([[110.8, 109.4, 0.44589999999999996, 0.3448, 0.8200999999999998, 41.2, 12.0, 5.8, 0.1, 1478.154539900302, 101.0, 104.1, 0.43470000000000003, 0.3276, 0.7188, 44.5, 16.6, 3.7, 0.6, 1564.2471699243392]]))